// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, default_planner_agent, default_planner_model, embedded_worker_path, worker_paths, created_at, updated_at, sort_index)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID                  string
	Name                string
	DefaultPlannerAgent string
	DefaultPlannerModel string
	EmbeddedWorkerPath  string
	WorkerPaths         string
	CreatedAt           string
	UpdatedAt           string
	SortIndex           int64
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.DefaultPlannerAgent,
		arg.DefaultPlannerModel,
		arg.EmbeddedWorkerPath,
		arg.WorkerPaths,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SortIndex,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execresult
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProject, id)
}

const getProject = `-- name: GetProject :one
SELECT id, name, default_planner_agent, default_planner_model, embedded_worker_path, worker_paths, created_at, updated_at, sort_index FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultPlannerAgent,
		&i.DefaultPlannerModel,
		&i.EmbeddedWorkerPath,
		&i.WorkerPaths,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortIndex,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, default_planner_agent, default_planner_model, embedded_worker_path, worker_paths, created_at, updated_at, sort_index FROM projects
ORDER BY sort_index, created_at
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultPlannerAgent,
			&i.DefaultPlannerModel,
			&i.EmbeddedWorkerPath,
			&i.WorkerPaths,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :execresult
UPDATE projects
SET name = ?, default_planner_agent = ?, default_planner_model = ?, embedded_worker_path = ?, worker_paths = ?, updated_at = ?, sort_index = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name                string
	DefaultPlannerAgent string
	DefaultPlannerModel string
	EmbeddedWorkerPath  string
	WorkerPaths         string
	UpdatedAt           string
	SortIndex           int64
	ID                  string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.DefaultPlannerAgent,
		arg.DefaultPlannerModel,
		arg.EmbeddedWorkerPath,
		arg.WorkerPaths,
		arg.UpdatedAt,
		arg.SortIndex,
		arg.ID,
	)
}
