// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :exec
INSERT INTO projects (id, name, default_planner_agent, default_planner_model, embedded_worker_path, worker_paths, created_at, updated_at, sort_index, agent_planning_task_preferences)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateProjectParams struct {
	ID                           string
	Name                         string
	DefaultPlannerAgent          string
	DefaultPlannerModel          string
	EmbeddedWorkerPath           string
	WorkerPaths                  string
	CreatedAt                    string
	UpdatedAt                    string
	SortIndex                    int64
	AgentPlanningTaskPreferences string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) error {
	_, err := q.db.ExecContext(ctx, createProject,
		arg.ID,
		arg.Name,
		arg.DefaultPlannerAgent,
		arg.DefaultPlannerModel,
		arg.EmbeddedWorkerPath,
		arg.WorkerPaths,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.SortIndex,
		arg.AgentPlanningTaskPreferences,
	)
	return err
}

const deleteProject = `-- name: DeleteProject :execresult
DELETE FROM projects WHERE id = ?
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteProject, id)
}

const deleteWorkerProjectPaths = `-- name: DeleteWorkerProjectPaths :exec
DELETE FROM worker_project_paths WHERE project_id = ?
`

func (q *Queries) DeleteWorkerProjectPaths(ctx context.Context, projectID string) error {
	_, err := q.db.ExecContext(ctx, deleteWorkerProjectPaths, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, name, default_planner_agent, default_planner_model, embedded_worker_path, worker_paths, created_at, updated_at, sort_index, agent_planning_task_preferences FROM projects
WHERE id = ?
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DefaultPlannerAgent,
		&i.DefaultPlannerModel,
		&i.EmbeddedWorkerPath,
		&i.WorkerPaths,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SortIndex,
		&i.AgentPlanningTaskPreferences,
	)
	return i, err
}

const insertWorkerProjectPath = `-- name: InsertWorkerProjectPath :exec
INSERT INTO worker_project_paths (project_id, worker_id, path)
VALUES (?, ?, ?)
`

type InsertWorkerProjectPathParams struct {
	ProjectID string
	WorkerID  string
	Path      string
}

func (q *Queries) InsertWorkerProjectPath(ctx context.Context, arg InsertWorkerProjectPathParams) error {
	_, err := q.db.ExecContext(ctx, insertWorkerProjectPath, arg.ProjectID, arg.WorkerID, arg.Path)
	return err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, default_planner_agent, default_planner_model, embedded_worker_path, worker_paths, created_at, updated_at, sort_index, agent_planning_task_preferences FROM projects
ORDER BY sort_index, created_at
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DefaultPlannerAgent,
			&i.DefaultPlannerModel,
			&i.EmbeddedWorkerPath,
			&i.WorkerPaths,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SortIndex,
			&i.AgentPlanningTaskPreferences,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkerProjectPaths = `-- name: ListWorkerProjectPaths :many
SELECT worker_id, path FROM worker_project_paths
WHERE project_id = ?
`

type ListWorkerProjectPathsRow struct {
	WorkerID string
	Path     string
}

func (q *Queries) ListWorkerProjectPaths(ctx context.Context, projectID string) ([]ListWorkerProjectPathsRow, error) {
	rows, err := q.db.QueryContext(ctx, listWorkerProjectPaths, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkerProjectPathsRow
	for rows.Next() {
		var i ListWorkerProjectPathsRow
		if err := rows.Scan(&i.WorkerID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :execresult
UPDATE projects
SET name = ?, default_planner_agent = ?, default_planner_model = ?, embedded_worker_path = ?, worker_paths = ?, updated_at = ?, sort_index = ?, agent_planning_task_preferences = ?
WHERE id = ?
`

type UpdateProjectParams struct {
	Name                         string
	DefaultPlannerAgent          string
	DefaultPlannerModel          string
	EmbeddedWorkerPath           string
	WorkerPaths                  string
	UpdatedAt                    string
	SortIndex                    int64
	AgentPlanningTaskPreferences string
	ID                           string
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProject,
		arg.Name,
		arg.DefaultPlannerAgent,
		arg.DefaultPlannerModel,
		arg.EmbeddedWorkerPath,
		arg.WorkerPaths,
		arg.UpdatedAt,
		arg.SortIndex,
		arg.AgentPlanningTaskPreferences,
		arg.ID,
	)
}
