// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createAgentRun = `-- name: CreateAgentRun :exec
INSERT INTO agent_runs (id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateAgentRunParams struct {
	ID        string
	ThreadID  string
	WorkerID  string
	Prompt    string
	Status    string
	Agent     string
	Model     string
	Mode      string
	Yolo      int64
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) error {
	_, err := q.db.ExecContext(ctx, createAgentRun,
		arg.ID,
		arg.ThreadID,
		arg.WorkerID,
		arg.Prompt,
		arg.Status,
		arg.Agent,
		arg.Model,
		arg.Mode,
		arg.Yolo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, session_id, created_at, updated_at FROM agent_runs
WHERE id = ?
`

func (q *Queries) GetAgentRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRowContext(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.WorkerID,
		&i.Prompt,
		&i.Status,
		&i.Agent,
		&i.Model,
		&i.Mode,
		&i.Yolo,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentRunsByThread = `-- name: ListAgentRunsByThread :many
SELECT id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, session_id, created_at, updated_at FROM agent_runs
WHERE thread_id = ?
ORDER BY created_at
`

func (q *Queries) ListAgentRunsByThread(ctx context.Context, threadID string) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listAgentRunsByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.WorkerID,
			&i.Prompt,
			&i.Status,
			&i.Agent,
			&i.Model,
			&i.Mode,
			&i.Yolo,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAgentRuns = `-- name: ListPendingAgentRuns :many
SELECT id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, session_id, created_at, updated_at FROM agent_runs
WHERE status = 'pending'
ORDER BY created_at
LIMIT ?
`

func (q *Queries) ListPendingAgentRuns(ctx context.Context, limit int64) ([]AgentRun, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAgentRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.WorkerID,
			&i.Prompt,
			&i.Status,
			&i.Agent,
			&i.Model,
			&i.Mode,
			&i.Yolo,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentRunStatus = `-- name: UpdateAgentRunStatus :execresult
UPDATE agent_runs
SET status = ?, session_id = ?, updated_at = ?
WHERE id = ?
`

type UpdateAgentRunStatusParams struct {
	Status    string
	SessionID string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateAgentRunStatus(ctx context.Context, arg UpdateAgentRunStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAgentRunStatus,
		arg.Status,
		arg.SessionID,
		arg.UpdatedAt,
		arg.ID,
	)
}
