// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createTask = `-- name: CreateTask :exec
INSERT INTO tasks (id, thread_id, description, subtasks, memory, status, sort_index, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateTaskParams struct {
	ID          string
	ThreadID    string
	Description string
	Subtasks    string
	Memory      string
	Status      string
	SortIndex   int64
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask,
		arg.ID,
		arg.ThreadID,
		arg.Description,
		arg.Subtasks,
		arg.Memory,
		arg.Status,
		arg.SortIndex,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = ?
`

func (q *Queries) DeleteTask(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, thread_id, description, subtasks, memory, status, sort_index, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Description,
		&i.Subtasks,
		&i.Memory,
		&i.Status,
		&i.SortIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTasksByThread = `-- name: ListTasksByThread :many
SELECT id, thread_id, description, subtasks, memory, status, sort_index, created_at, updated_at FROM tasks WHERE thread_id = ? ORDER BY sort_index, created_at
`

func (q *Queries) ListTasksByThread(ctx context.Context, threadID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Description,
			&i.Subtasks,
			&i.Memory,
			&i.Status,
			&i.SortIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :execresult
UPDATE tasks
SET description = ?, subtasks = ?, memory = ?, status = ?, sort_index = ?, updated_at = ?
WHERE id = ?
`

type UpdateTaskParams struct {
	Description string
	Subtasks    string
	Memory      string
	Status      string
	SortIndex   int64
	UpdatedAt   string
	ID          string
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTask,
		arg.Description,
		arg.Subtasks,
		arg.Memory,
		arg.Status,
		arg.SortIndex,
		arg.UpdatedAt,
		arg.ID,
	)
}
