// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createThread = `-- name: CreateThread :exec
INSERT INTO threads (id, project_id, agent, model, mode, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateThreadParams struct {
	ID        string
	ProjectID string
	Agent     string
	Model     string
	Mode      string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) error {
	_, err := q.db.ExecContext(ctx, createThread,
		arg.ID,
		arg.ProjectID,
		arg.Agent,
		arg.Model,
		arg.Mode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteThread = `-- name: DeleteThread :execresult
DELETE FROM threads WHERE id = ?
`

func (q *Queries) DeleteThread(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteThread, id)
}

const getThread = `-- name: GetThread :one
SELECT id, project_id, agent, model, created_at, updated_at, mode, topic, archived, "plan" FROM threads
WHERE id = ?
`

func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Agent,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.Topic,
		&i.Archived,
		&i.Plan,
	)
	return i, err
}

const listThreads = `-- name: ListThreads :many
SELECT id, project_id, agent, model, created_at, updated_at, mode, topic, archived, "plan" FROM threads
WHERE project_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListThreads(ctx context.Context, projectID string) ([]Thread, error) {
	rows, err := q.db.QueryContext(ctx, listThreads, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Thread
	for rows.Next() {
		var i Thread
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Agent,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.Topic,
			&i.Archived,
			&i.Plan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateThread = `-- name: UpdateThread :execresult
UPDATE threads
SET agent = ?, model = ?, updated_at = ?
WHERE id = ?
`

type UpdateThreadParams struct {
	Agent     string
	Model     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateThread(ctx context.Context, arg UpdateThreadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateThread,
		arg.Agent,
		arg.Model,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateThreadArchived = `-- name: UpdateThreadArchived :execresult
UPDATE threads
SET archived = ?, updated_at = ?
WHERE id = ?
`

type UpdateThreadArchivedParams struct {
	Archived  int64
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateThreadArchived(ctx context.Context, arg UpdateThreadArchivedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateThreadArchived, arg.Archived, arg.UpdatedAt, arg.ID)
}

const updateThreadPlan = `-- name: UpdateThreadPlan :execresult
UPDATE threads
SET plan = ?, updated_at = ?
WHERE id = ?
`

type UpdateThreadPlanParams struct {
	Plan      string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateThreadPlan(ctx context.Context, arg UpdateThreadPlanParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateThreadPlan, arg.Plan, arg.UpdatedAt, arg.ID)
}

const updateThreadTopic = `-- name: UpdateThreadTopic :execresult
UPDATE threads
SET topic = ?, updated_at = ?
WHERE id = ?
`

type UpdateThreadTopicParams struct {
	Topic     string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateThreadTopic(ctx context.Context, arg UpdateThreadTopicParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateThreadTopic, arg.Topic, arg.UpdatedAt, arg.ID)
}
