// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

type Project struct {
	ID                  string
	Name                string
	DefaultPlannerAgent string
	DefaultPlannerModel string
	EmbeddedWorkerPath  string
	WorkerPaths         string
	CreatedAt           string
	UpdatedAt           string
	SortIndex           int64
}

type Thread struct {
	ID        string
	ProjectID string
	Agent     string
	Model     string
	CreatedAt string
	UpdatedAt string
}

type Worker struct {
	ID        string
	Name      string
	Url       string
	Secret    string
	CreatedAt string
	UpdatedAt string
}
