// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createWorker = `-- name: CreateWorker :exec
INSERT INTO workers (id, name, url, secret, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWorkerParams struct {
	ID        string
	Name      string
	Url       string
	Secret    string
	CreatedAt string
	UpdatedAt string
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) error {
	_, err := q.db.ExecContext(ctx, createWorker,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteWorker = `-- name: DeleteWorker :execresult
DELETE FROM workers WHERE id = ?
`

func (q *Queries) DeleteWorker(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteWorker, id)
}

const getWorker = `-- name: GetWorker :one
SELECT id, name, url, secret, created_at, updated_at FROM workers
WHERE id = ?
`

func (q *Queries) GetWorker(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, name, url, secret, created_at, updated_at FROM workers
ORDER BY created_at
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :execresult
UPDATE workers
SET name = ?, url = ?, secret = ?, updated_at = ?
WHERE id = ?
`

type UpdateWorkerParams struct {
	Name      string
	Url       string
	Secret    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWorker,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.UpdatedAt,
		arg.ID,
	)
}
