// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
)

const getSecret = `-- name: GetSecret :one
SELECT secret FROM embedded_worker_config WHERE id = 1
`

func (q *Queries) GetSecret(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSecret)
	var secret string
	err := row.Scan(&secret)
	return secret, err
}

const upsertSecret = `-- name: UpsertSecret :exec
INSERT INTO embedded_worker_config (id, secret)
VALUES (1, ?)
ON CONFLICT (id) DO UPDATE SET secret = excluded.secret
`

func (q *Queries) UpsertSecret(ctx context.Context, secret string) error {
	_, err := q.db.ExecContext(ctx, upsertSecret, secret)
	return err
}
