/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppTestRouteImport } from './routes/app/test'
import { Route as AppThreadsRouteRouteImport } from './routes/app/threads/route'
import { Route as AppTasksRouteRouteImport } from './routes/app/tasks/route'
import { Route as AppThreadsIndexRouteImport } from './routes/app/threads/index'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppThreadsThreadIdRouteRouteImport } from './routes/app/threads/$threadId/route'
import { Route as AppDemoScenarioIdRouteRouteImport } from './routes/app/demo/$scenarioId/route'
import { Route as AppThreadsThreadIdIndexRouteImport } from './routes/app/threads/$threadId/index'
import { Route as AppThreadsThreadIdMemoryRouteImport } from './routes/app/threads/$threadId/memory'
import { Route as AppThreadsThreadIdCheckinsRouteImport } from './routes/app/threads/$threadId/checkins'
import { Route as AppThreadsThreadIdChangesRouteImport } from './routes/app/threads/$threadId/changes'
import { Route as AppThreadsThreadIdTasksRouteRouteImport } from './routes/app/threads/$threadId/tasks/route'
import { Route as AppTasksThreadIdTaskIdRouteRouteImport } from './routes/app/tasks/$threadId/$taskId/route'
import { Route as AppThreadsThreadIdTasksIndexRouteImport } from './routes/app/threads/$threadId/tasks/index'
import { Route as AppTasksThreadIdTaskIdIndexRouteImport } from './routes/app/tasks/$threadId/$taskId/index'
import { Route as AppTasksThreadIdTaskIdProgressRouteImport } from './routes/app/tasks/$threadId/$taskId/progress'
import { Route as AppTasksThreadIdTaskIdMemoryRouteImport } from './routes/app/tasks/$threadId/$taskId/memory'
import { Route as AppTasksThreadIdTaskIdChangesRouteImport } from './routes/app/tasks/$threadId/$taskId/changes'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTestRoute = AppTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppThreadsRouteRoute = AppThreadsRouteRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTasksRouteRoute = AppTasksRouteRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppThreadsIndexRoute = AppThreadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppThreadsThreadIdRouteRoute = AppThreadsThreadIdRouteRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => AppThreadsRouteRoute,
} as any)
const AppDemoScenarioIdRouteRoute = AppDemoScenarioIdRouteRouteImport.update({
  id: '/demo/$scenarioId',
  path: '/demo/$scenarioId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppThreadsThreadIdIndexRoute = AppThreadsThreadIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppThreadsThreadIdRouteRoute,
} as any)
const AppThreadsThreadIdMemoryRoute =
  AppThreadsThreadIdMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => AppThreadsThreadIdRouteRoute,
  } as any)
const AppThreadsThreadIdCheckinsRoute =
  AppThreadsThreadIdCheckinsRouteImport.update({
    id: '/checkins',
    path: '/checkins',
    getParentRoute: () => AppThreadsThreadIdRouteRoute,
  } as any)
const AppThreadsThreadIdChangesRoute =
  AppThreadsThreadIdChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => AppThreadsThreadIdRouteRoute,
  } as any)
const AppThreadsThreadIdTasksRouteRoute =
  AppThreadsThreadIdTasksRouteRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AppThreadsThreadIdRouteRoute,
  } as any)
const AppTasksThreadIdTaskIdRouteRoute =
  AppTasksThreadIdTaskIdRouteRouteImport.update({
    id: '/$threadId/$taskId',
    path: '/$threadId/$taskId',
    getParentRoute: () => AppTasksRouteRoute,
  } as any)
const AppThreadsThreadIdTasksIndexRoute =
  AppThreadsThreadIdTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppThreadsThreadIdTasksRouteRoute,
  } as any)
const AppTasksThreadIdTaskIdIndexRoute =
  AppTasksThreadIdTaskIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppTasksThreadIdTaskIdRouteRoute,
  } as any)
const AppTasksThreadIdTaskIdProgressRoute =
  AppTasksThreadIdTaskIdProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AppTasksThreadIdTaskIdRouteRoute,
  } as any)
const AppTasksThreadIdTaskIdMemoryRoute =
  AppTasksThreadIdTaskIdMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => AppTasksThreadIdTaskIdRouteRoute,
  } as any)
const AppTasksThreadIdTaskIdChangesRoute =
  AppTasksThreadIdTaskIdChangesRouteImport.update({
    id: '/changes',
    path: '/changes',
    getParentRoute: () => AppTasksThreadIdTaskIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/test': typeof TestRoute
  '/app/tasks': typeof AppTasksRouteRouteWithChildren
  '/app/threads': typeof AppThreadsRouteRouteWithChildren
  '/app/test': typeof AppTestRoute
  '/app/': typeof AppIndexRoute
  '/app/demo/$scenarioId': typeof AppDemoScenarioIdRouteRoute
  '/app/threads/$threadId': typeof AppThreadsThreadIdRouteRouteWithChildren
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/threads/': typeof AppThreadsIndexRoute
  '/app/tasks/$threadId/$taskId': typeof AppTasksThreadIdTaskIdRouteRouteWithChildren
  '/app/threads/$threadId/tasks': typeof AppThreadsThreadIdTasksRouteRouteWithChildren
  '/app/threads/$threadId/changes': typeof AppThreadsThreadIdChangesRoute
  '/app/threads/$threadId/checkins': typeof AppThreadsThreadIdCheckinsRoute
  '/app/threads/$threadId/memory': typeof AppThreadsThreadIdMemoryRoute
  '/app/threads/$threadId/': typeof AppThreadsThreadIdIndexRoute
  '/app/tasks/$threadId/$taskId/changes': typeof AppTasksThreadIdTaskIdChangesRoute
  '/app/tasks/$threadId/$taskId/memory': typeof AppTasksThreadIdTaskIdMemoryRoute
  '/app/tasks/$threadId/$taskId/progress': typeof AppTasksThreadIdTaskIdProgressRoute
  '/app/tasks/$threadId/$taskId/': typeof AppTasksThreadIdTaskIdIndexRoute
  '/app/threads/$threadId/tasks/': typeof AppThreadsThreadIdTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test': typeof TestRoute
  '/app/tasks': typeof AppTasksRouteRouteWithChildren
  '/app/test': typeof AppTestRoute
  '/app': typeof AppIndexRoute
  '/app/demo/$scenarioId': typeof AppDemoScenarioIdRouteRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/threads': typeof AppThreadsIndexRoute
  '/app/threads/$threadId/changes': typeof AppThreadsThreadIdChangesRoute
  '/app/threads/$threadId/checkins': typeof AppThreadsThreadIdCheckinsRoute
  '/app/threads/$threadId/memory': typeof AppThreadsThreadIdMemoryRoute
  '/app/threads/$threadId': typeof AppThreadsThreadIdIndexRoute
  '/app/tasks/$threadId/$taskId/changes': typeof AppTasksThreadIdTaskIdChangesRoute
  '/app/tasks/$threadId/$taskId/memory': typeof AppTasksThreadIdTaskIdMemoryRoute
  '/app/tasks/$threadId/$taskId/progress': typeof AppTasksThreadIdTaskIdProgressRoute
  '/app/tasks/$threadId/$taskId': typeof AppTasksThreadIdTaskIdIndexRoute
  '/app/threads/$threadId/tasks': typeof AppThreadsThreadIdTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/test': typeof TestRoute
  '/app/tasks': typeof AppTasksRouteRouteWithChildren
  '/app/threads': typeof AppThreadsRouteRouteWithChildren
  '/app/test': typeof AppTestRoute
  '/app/': typeof AppIndexRoute
  '/app/demo/$scenarioId': typeof AppDemoScenarioIdRouteRoute
  '/app/threads/$threadId': typeof AppThreadsThreadIdRouteRouteWithChildren
  '/app/settings/': typeof AppSettingsIndexRoute
  '/app/threads/': typeof AppThreadsIndexRoute
  '/app/tasks/$threadId/$taskId': typeof AppTasksThreadIdTaskIdRouteRouteWithChildren
  '/app/threads/$threadId/tasks': typeof AppThreadsThreadIdTasksRouteRouteWithChildren
  '/app/threads/$threadId/changes': typeof AppThreadsThreadIdChangesRoute
  '/app/threads/$threadId/checkins': typeof AppThreadsThreadIdCheckinsRoute
  '/app/threads/$threadId/memory': typeof AppThreadsThreadIdMemoryRoute
  '/app/threads/$threadId/': typeof AppThreadsThreadIdIndexRoute
  '/app/tasks/$threadId/$taskId/changes': typeof AppTasksThreadIdTaskIdChangesRoute
  '/app/tasks/$threadId/$taskId/memory': typeof AppTasksThreadIdTaskIdMemoryRoute
  '/app/tasks/$threadId/$taskId/progress': typeof AppTasksThreadIdTaskIdProgressRoute
  '/app/tasks/$threadId/$taskId/': typeof AppTasksThreadIdTaskIdIndexRoute
  '/app/threads/$threadId/tasks/': typeof AppThreadsThreadIdTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/test'
    | '/app/tasks'
    | '/app/threads'
    | '/app/test'
    | '/app/'
    | '/app/demo/$scenarioId'
    | '/app/threads/$threadId'
    | '/app/settings/'
    | '/app/threads/'
    | '/app/tasks/$threadId/$taskId'
    | '/app/threads/$threadId/tasks'
    | '/app/threads/$threadId/changes'
    | '/app/threads/$threadId/checkins'
    | '/app/threads/$threadId/memory'
    | '/app/threads/$threadId/'
    | '/app/tasks/$threadId/$taskId/changes'
    | '/app/tasks/$threadId/$taskId/memory'
    | '/app/tasks/$threadId/$taskId/progress'
    | '/app/tasks/$threadId/$taskId/'
    | '/app/threads/$threadId/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test'
    | '/app/tasks'
    | '/app/test'
    | '/app'
    | '/app/demo/$scenarioId'
    | '/app/settings'
    | '/app/threads'
    | '/app/threads/$threadId/changes'
    | '/app/threads/$threadId/checkins'
    | '/app/threads/$threadId/memory'
    | '/app/threads/$threadId'
    | '/app/tasks/$threadId/$taskId/changes'
    | '/app/tasks/$threadId/$taskId/memory'
    | '/app/tasks/$threadId/$taskId/progress'
    | '/app/tasks/$threadId/$taskId'
    | '/app/threads/$threadId/tasks'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/test'
    | '/app/tasks'
    | '/app/threads'
    | '/app/test'
    | '/app/'
    | '/app/demo/$scenarioId'
    | '/app/threads/$threadId'
    | '/app/settings/'
    | '/app/threads/'
    | '/app/tasks/$threadId/$taskId'
    | '/app/threads/$threadId/tasks'
    | '/app/threads/$threadId/changes'
    | '/app/threads/$threadId/checkins'
    | '/app/threads/$threadId/memory'
    | '/app/threads/$threadId/'
    | '/app/tasks/$threadId/$taskId/changes'
    | '/app/tasks/$threadId/$taskId/memory'
    | '/app/tasks/$threadId/$taskId/progress'
    | '/app/tasks/$threadId/$taskId/'
    | '/app/threads/$threadId/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/test': {
      id: '/app/test'
      path: '/test'
      fullPath: '/app/test'
      preLoaderRoute: typeof AppTestRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/threads': {
      id: '/app/threads'
      path: '/threads'
      fullPath: '/app/threads'
      preLoaderRoute: typeof AppThreadsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/threads/': {
      id: '/app/threads/'
      path: '/'
      fullPath: '/app/threads/'
      preLoaderRoute: typeof AppThreadsIndexRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/settings'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/threads/$threadId': {
      id: '/app/threads/$threadId'
      path: '/$threadId'
      fullPath: '/app/threads/$threadId'
      preLoaderRoute: typeof AppThreadsThreadIdRouteRouteImport
      parentRoute: typeof AppThreadsRouteRoute
    }
    '/app/demo/$scenarioId': {
      id: '/app/demo/$scenarioId'
      path: '/demo/$scenarioId'
      fullPath: '/app/demo/$scenarioId'
      preLoaderRoute: typeof AppDemoScenarioIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/threads/$threadId/': {
      id: '/app/threads/$threadId/'
      path: '/'
      fullPath: '/app/threads/$threadId/'
      preLoaderRoute: typeof AppThreadsThreadIdIndexRouteImport
      parentRoute: typeof AppThreadsThreadIdRouteRoute
    }
    '/app/threads/$threadId/memory': {
      id: '/app/threads/$threadId/memory'
      path: '/memory'
      fullPath: '/app/threads/$threadId/memory'
      preLoaderRoute: typeof AppThreadsThreadIdMemoryRouteImport
      parentRoute: typeof AppThreadsThreadIdRouteRoute
    }
    '/app/threads/$threadId/checkins': {
      id: '/app/threads/$threadId/checkins'
      path: '/checkins'
      fullPath: '/app/threads/$threadId/checkins'
      preLoaderRoute: typeof AppThreadsThreadIdCheckinsRouteImport
      parentRoute: typeof AppThreadsThreadIdRouteRoute
    }
    '/app/threads/$threadId/changes': {
      id: '/app/threads/$threadId/changes'
      path: '/changes'
      fullPath: '/app/threads/$threadId/changes'
      preLoaderRoute: typeof AppThreadsThreadIdChangesRouteImport
      parentRoute: typeof AppThreadsThreadIdRouteRoute
    }
    '/app/threads/$threadId/tasks': {
      id: '/app/threads/$threadId/tasks'
      path: '/tasks'
      fullPath: '/app/threads/$threadId/tasks'
      preLoaderRoute: typeof AppThreadsThreadIdTasksRouteRouteImport
      parentRoute: typeof AppThreadsThreadIdRouteRoute
    }
    '/app/tasks/$threadId/$taskId': {
      id: '/app/tasks/$threadId/$taskId'
      path: '/$threadId/$taskId'
      fullPath: '/app/tasks/$threadId/$taskId'
      preLoaderRoute: typeof AppTasksThreadIdTaskIdRouteRouteImport
      parentRoute: typeof AppTasksRouteRoute
    }
    '/app/threads/$threadId/tasks/': {
      id: '/app/threads/$threadId/tasks/'
      path: '/'
      fullPath: '/app/threads/$threadId/tasks/'
      preLoaderRoute: typeof AppThreadsThreadIdTasksIndexRouteImport
      parentRoute: typeof AppThreadsThreadIdTasksRouteRoute
    }
    '/app/tasks/$threadId/$taskId/': {
      id: '/app/tasks/$threadId/$taskId/'
      path: '/'
      fullPath: '/app/tasks/$threadId/$taskId/'
      preLoaderRoute: typeof AppTasksThreadIdTaskIdIndexRouteImport
      parentRoute: typeof AppTasksThreadIdTaskIdRouteRoute
    }
    '/app/tasks/$threadId/$taskId/progress': {
      id: '/app/tasks/$threadId/$taskId/progress'
      path: '/progress'
      fullPath: '/app/tasks/$threadId/$taskId/progress'
      preLoaderRoute: typeof AppTasksThreadIdTaskIdProgressRouteImport
      parentRoute: typeof AppTasksThreadIdTaskIdRouteRoute
    }
    '/app/tasks/$threadId/$taskId/memory': {
      id: '/app/tasks/$threadId/$taskId/memory'
      path: '/memory'
      fullPath: '/app/tasks/$threadId/$taskId/memory'
      preLoaderRoute: typeof AppTasksThreadIdTaskIdMemoryRouteImport
      parentRoute: typeof AppTasksThreadIdTaskIdRouteRoute
    }
    '/app/tasks/$threadId/$taskId/changes': {
      id: '/app/tasks/$threadId/$taskId/changes'
      path: '/changes'
      fullPath: '/app/tasks/$threadId/$taskId/changes'
      preLoaderRoute: typeof AppTasksThreadIdTaskIdChangesRouteImport
      parentRoute: typeof AppTasksThreadIdTaskIdRouteRoute
    }
  }
}

interface AppTasksThreadIdTaskIdRouteRouteChildren {
  AppTasksThreadIdTaskIdChangesRoute: typeof AppTasksThreadIdTaskIdChangesRoute
  AppTasksThreadIdTaskIdMemoryRoute: typeof AppTasksThreadIdTaskIdMemoryRoute
  AppTasksThreadIdTaskIdProgressRoute: typeof AppTasksThreadIdTaskIdProgressRoute
  AppTasksThreadIdTaskIdIndexRoute: typeof AppTasksThreadIdTaskIdIndexRoute
}

const AppTasksThreadIdTaskIdRouteRouteChildren: AppTasksThreadIdTaskIdRouteRouteChildren =
  {
    AppTasksThreadIdTaskIdChangesRoute: AppTasksThreadIdTaskIdChangesRoute,
    AppTasksThreadIdTaskIdMemoryRoute: AppTasksThreadIdTaskIdMemoryRoute,
    AppTasksThreadIdTaskIdProgressRoute: AppTasksThreadIdTaskIdProgressRoute,
    AppTasksThreadIdTaskIdIndexRoute: AppTasksThreadIdTaskIdIndexRoute,
  }

const AppTasksThreadIdTaskIdRouteRouteWithChildren =
  AppTasksThreadIdTaskIdRouteRoute._addFileChildren(
    AppTasksThreadIdTaskIdRouteRouteChildren,
  )

interface AppTasksRouteRouteChildren {
  AppTasksThreadIdTaskIdRouteRoute: typeof AppTasksThreadIdTaskIdRouteRouteWithChildren
}

const AppTasksRouteRouteChildren: AppTasksRouteRouteChildren = {
  AppTasksThreadIdTaskIdRouteRoute:
    AppTasksThreadIdTaskIdRouteRouteWithChildren,
}

const AppTasksRouteRouteWithChildren = AppTasksRouteRoute._addFileChildren(
  AppTasksRouteRouteChildren,
)

interface AppThreadsThreadIdTasksRouteRouteChildren {
  AppThreadsThreadIdTasksIndexRoute: typeof AppThreadsThreadIdTasksIndexRoute
}

const AppThreadsThreadIdTasksRouteRouteChildren: AppThreadsThreadIdTasksRouteRouteChildren =
  {
    AppThreadsThreadIdTasksIndexRoute: AppThreadsThreadIdTasksIndexRoute,
  }

const AppThreadsThreadIdTasksRouteRouteWithChildren =
  AppThreadsThreadIdTasksRouteRoute._addFileChildren(
    AppThreadsThreadIdTasksRouteRouteChildren,
  )

interface AppThreadsThreadIdRouteRouteChildren {
  AppThreadsThreadIdTasksRouteRoute: typeof AppThreadsThreadIdTasksRouteRouteWithChildren
  AppThreadsThreadIdChangesRoute: typeof AppThreadsThreadIdChangesRoute
  AppThreadsThreadIdCheckinsRoute: typeof AppThreadsThreadIdCheckinsRoute
  AppThreadsThreadIdMemoryRoute: typeof AppThreadsThreadIdMemoryRoute
  AppThreadsThreadIdIndexRoute: typeof AppThreadsThreadIdIndexRoute
}

const AppThreadsThreadIdRouteRouteChildren: AppThreadsThreadIdRouteRouteChildren =
  {
    AppThreadsThreadIdTasksRouteRoute:
      AppThreadsThreadIdTasksRouteRouteWithChildren,
    AppThreadsThreadIdChangesRoute: AppThreadsThreadIdChangesRoute,
    AppThreadsThreadIdCheckinsRoute: AppThreadsThreadIdCheckinsRoute,
    AppThreadsThreadIdMemoryRoute: AppThreadsThreadIdMemoryRoute,
    AppThreadsThreadIdIndexRoute: AppThreadsThreadIdIndexRoute,
  }

const AppThreadsThreadIdRouteRouteWithChildren =
  AppThreadsThreadIdRouteRoute._addFileChildren(
    AppThreadsThreadIdRouteRouteChildren,
  )

interface AppThreadsRouteRouteChildren {
  AppThreadsThreadIdRouteRoute: typeof AppThreadsThreadIdRouteRouteWithChildren
  AppThreadsIndexRoute: typeof AppThreadsIndexRoute
}

const AppThreadsRouteRouteChildren: AppThreadsRouteRouteChildren = {
  AppThreadsThreadIdRouteRoute: AppThreadsThreadIdRouteRouteWithChildren,
  AppThreadsIndexRoute: AppThreadsIndexRoute,
}

const AppThreadsRouteRouteWithChildren = AppThreadsRouteRoute._addFileChildren(
  AppThreadsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppTasksRouteRoute: typeof AppTasksRouteRouteWithChildren
  AppThreadsRouteRoute: typeof AppThreadsRouteRouteWithChildren
  AppTestRoute: typeof AppTestRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDemoScenarioIdRouteRoute: typeof AppDemoScenarioIdRouteRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppTasksRouteRoute: AppTasksRouteRouteWithChildren,
  AppThreadsRouteRoute: AppThreadsRouteRouteWithChildren,
  AppTestRoute: AppTestRoute,
  AppIndexRoute: AppIndexRoute,
  AppDemoScenarioIdRouteRoute: AppDemoScenarioIdRouteRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
