// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, thread_id, worker_id, prompt, status, agent, model, mode, session_mode, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID          string
	ThreadID    string
	WorkerID    string
	Prompt      string
	Status      string
	Agent       string
	Model       string
	Mode        string
	SessionMode string
	CreatedAt   string
	UpdatedAt   string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.ThreadID,
		arg.WorkerID,
		arg.Prompt,
		arg.Status,
		arg.Agent,
		arg.Model,
		arg.Mode,
		arg.SessionMode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getEmbeddedWorkerPathForSession = `-- name: GetEmbeddedWorkerPathForSession :one
SELECT p.embedded_worker_path
FROM sessions s
JOIN threads t ON t.id = s.thread_id
JOIN projects p ON p.id = t.project_id
WHERE s.id = ?
`

func (q *Queries) GetEmbeddedWorkerPathForSession(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getEmbeddedWorkerPathForSession, id)
	var embedded_worker_path string
	err := row.Scan(&embedded_worker_path)
	return embedded_worker_path, err
}

const getSession = `-- name: GetSession :one
SELECT id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, session_id, created_at, updated_at, session_mode, task_id FROM sessions
WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.WorkerID,
		&i.Prompt,
		&i.Status,
		&i.Agent,
		&i.Model,
		&i.Mode,
		&i.Yolo,
		&i.SessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SessionMode,
		&i.TaskID,
	)
	return i, err
}

const getWorkerProjectPath = `-- name: GetWorkerProjectPath :one
SELECT path FROM worker_project_paths
WHERE project_id = ? AND worker_id = ?
`

type GetWorkerProjectPathParams struct {
	ProjectID string
	WorkerID  string
}

func (q *Queries) GetWorkerProjectPath(ctx context.Context, arg GetWorkerProjectPathParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getWorkerProjectPath, arg.ProjectID, arg.WorkerID)
	var path string
	err := row.Scan(&path)
	return path, err
}

const insertSessionEvent = `-- name: InsertSessionEvent :exec
INSERT INTO session_events (session_id, sequence, event_type, payload, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertSessionEventParams struct {
	SessionID string
	Sequence  int64
	EventType string
	Payload   []byte
	CreatedAt string
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionEvent,
		arg.SessionID,
		arg.Sequence,
		arg.EventType,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const listPendingSessions = `-- name: ListPendingSessions :many
SELECT id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, session_id, created_at, updated_at, session_mode, task_id FROM sessions
WHERE status = 'pending'
ORDER BY created_at
LIMIT ?
`

func (q *Queries) ListPendingSessions(ctx context.Context, limit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listPendingSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.WorkerID,
			&i.Prompt,
			&i.Status,
			&i.Agent,
			&i.Model,
			&i.Mode,
			&i.Yolo,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionMode,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsBySession = `-- name: ListSessionEventsBySession :many
SELECT id, session_id, sequence, event_type, payload, created_at FROM session_events
WHERE session_id = ?
ORDER BY sequence ASC
`

func (q *Queries) ListSessionEventsBySession(ctx context.Context, sessionID string) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsByTask = `-- name: ListSessionEventsByTask :many
SELECT se.id, se.session_id, se.sequence, se.event_type, se.payload, se.created_at FROM session_events se
JOIN sessions s ON s.id = se.session_id
WHERE s.task_id = ?
ORDER BY se.sequence ASC
`

func (q *Queries) ListSessionEventsByTask(ctx context.Context, taskID sql.NullString) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionEventsByThread = `-- name: ListSessionEventsByThread :many
SELECT se.id, se.session_id, se.sequence, se.event_type, se.payload, se.created_at FROM session_events se
JOIN sessions s ON s.id = se.session_id
WHERE s.thread_id = ?
ORDER BY se.sequence ASC
`

func (q *Queries) ListSessionEventsByThread(ctx context.Context, threadID string) ([]SessionEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSessionEventsByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionEvent
	for rows.Next() {
		var i SessionEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Sequence,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByThread = `-- name: ListSessionsByThread :many
SELECT id, thread_id, worker_id, prompt, status, agent, model, mode, yolo, session_id, created_at, updated_at, session_mode, task_id FROM sessions
WHERE thread_id = ?
ORDER BY created_at
`

func (q *Queries) ListSessionsByThread(ctx context.Context, threadID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.WorkerID,
			&i.Prompt,
			&i.Status,
			&i.Agent,
			&i.Model,
			&i.Mode,
			&i.Yolo,
			&i.SessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SessionMode,
			&i.TaskID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionStatus = `-- name: UpdateSessionStatus :execresult
UPDATE sessions
SET session_id = ?, status = ?, updated_at = ?
WHERE id = ?
`

type UpdateSessionStatusParams struct {
	SessionID string
	Status    string
	UpdatedAt string
	ID        string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSessionStatus,
		arg.SessionID,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
	)
}
